### ISSUE TITLE
system for ontology term request ticket management

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#1]
Our aim is to offer the ontology maintainers a ticket management system that they could take or leave (another tool in their toolbox), if they would rather use their own system, our function would be redirecting the ticket to their system.

**Comment by chung88** [comment]
Redirect of the ticket to other systems (via email) has been implemented. 
confirmed by @whinis 02/24/2020 2:20 PM via slack:  Yes
