### ISSUE TITLE
Implement Term Request Manager

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#13]
Assigned tasks for this component so far:

- Figure out ont mgr
- Get their contact route
- Sending some kind of notice
- Pre-processing (deciding on the ontology, determine if there is a design pattern associated, etc.)
-

**Comment by whinis** [comment]
This should be completed as it was previously, need others to confirm

**Comment by whinis** [comment]
@handemcginty This code is contained within https://github.com/OntoloBridge/ontolobridge-project/blob/master/src/main/java/edu/miami/schurer/ontolobridge/OntologyManagerService.java
