### ISSUE TITLE
Implement Term Request Receiver Agent

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#14]
assigned roles for this component so far:

- Manage state
- (interacts w/data store)
- Track tickets
- Create ticket
- Respond with ReqID

**Comment by whinis** [comment]
This code is contained with https://github.com/OntoloBridge/ontolobridge-project/blob/master/src/main/java/edu/miami/schurer/ontolobridge/RequestController.java
