### ISSUE TITLE
Implement Ontology Manager agent

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#15]
Tasks identified for it for now: 

- Holds all the info for all the available ontologies (i.e. design patterns for term request, update, etc.)
- Notify the ontology manager

**Comment by whinis** [comment]
This has been completed minus the connection to bioportal as discussed

**Comment by handemcginty** [comment]
ok, I am testing the components.

**Comment by handemcginty** [comment]
this looks like it's working, but I am wondering if you can direct me to the code @whinis ?

**Comment by whinis** [comment]
https://github.com/OntoloBridge/ontolobridge-project/blob/master/src/main/java/edu/miami/schurer/ontolobridge/OntologyManagerService.java

Specifically the CheckNewNotifications function
