### ISSUE TITLE
Implement the notifier

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#17]
tasks identified for it for now: 

- Push notifications of changes  (would require callback URL?)

-

**Comment by whinis** [comment]
This has been completed for emails

**Comment by handemcginty** [comment]
did we get the domain email as well?

**Comment by whinis** [comment]
No but I believe that is not required for the notifier to work, maybe another issue ?

**Comment by handemcginty** [comment]
alright, testing this.

**Comment by handemcginty** [comment]
I will provide templates for this and @whinis will make sure they go on as they should.

**Comment by handemcginty** [comment]
Also, @whinis please direct me to the code for this, thanks.

**Comment by whinis** [comment]
https://github.com/OntoloBridge/ontolobridge-project/blob/master/src/main/java/edu/miami/schurer/ontolobridge/NotifierService.java

**Comment by handemcginty** [comment]
Stephan had an idea about how the notifications might work. I am putting this as a note to keep track of the integration:
We can track requesters in two ways: verification emails or account creation.

Verification email:
ask the user to submit an email address, and have it verified before changing the request status to "pending" (to avoid junk requests)
Account creation with email verification
ask the user to create and verify an account for requests.

Disclaimer: below is clearly out of scope for this project, but is entered as a note.
-- We can think of integration of requests to GitHub when the account has "admin" status (some questions that need answers: how do we decide on admin status? how do we keep track? )
-- we can think of more ways for spam detection (perhaps pre-processing? maybe other options?)
-- OntoJog/Robot integration, automation of ontology forwarding with pre-processing
@sschurer please feel free to modify and add as you see fit, just noted bullet points to remind us our ideas.

**Comment by chung88** [comment]
@whinis  slack 2/25/2020 1:11 PM  notifier is done and [account request](https://github.com/OntoloBridge/ontolobridge-project/issues/46) is an extra feature
