### ISSUE TITLE
Update OntoJog for Preprocessing Term Requests

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#2]
Ideally, once a term request is submitted, we would like to guide the user to the appropriate next steps (provide more data using existing templates, identify if the term is already matching with an existing term, etc.) and have the system connect with the correct ontology for term request.

**Comment by whinis** [comment]
This is currently more of a stretch and more part of standalone UI

**Comment by chung88** [comment]
Outside the scope, reference:  [Standalone UI git issue # 40](https://github.com/OntoloBridge/ontolobridge-project/issues/40)
