### ISSUE TITLE
Build PubChem export tools

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#20]
Implement tools that will allow BAE and PubChem work together.
Work by CDD

**Comment by sjeschonek** [comment]
Update from Jason Harris at CDD who worked on this: 

 So, yes this is complete except after reading the aim it appears we also said that it would be automatically uploaded to PubChem through an API of sorts. PubChem gave us the option to point their team to our own FTP site where we they could automatically import any new release of our CDD Classification Tree. We determined that the updates would be ad hoc at this point so our current procedure is to email the PubChem team with a link whenever we have a new Tree to send.
