### ISSUE TITLE
create and conduct testing and evaluation workflows

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#24]
Although testing and evaluation will be performed in every step and after every deliverable, a more comprehensive testing will be applied and perhaps user testing can be incorporated to generate proper evaluation.

1. Decide on a QC/testing process
2. Perform the QC/testing using tools and methodologies generated/tools methods already existing
3. Perform assay related/ biologically relevant evaluation based on annotated assays? Perhaps LINCS/ BD2K assays?

**Comment by sjeschonek** [comment]
Closing this task as I am breaking it down into smaller goals/deliverables
