### ISSUE TITLE
Create Use cases document

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#26]
Using the existing document and notes on this document: https://docs.google.com/spreadsheets/d/1-aqgh3fJ1gyrJ4cbS9p1p98giHd60ZZJH2KsBzBhN4o/edit#gid=327920891

create proper use cases.

**Comment by chung88** [comment]
[Technical Proposal OntoloBridge](https://docs.google.com/document/d/1vB9PGXied4gdIXaFHfXyrOg67Nv2y8bTvmeR9LNJgII/edit?usp=sharing)
