### ISSUE TITLE
Review API update requests

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#3]
These edit requests are for the API specs located at:

    https://drive.google.com/drive/folders/1yXpC9kGscxTePsjOkP-VRnSJe55v8Mld

Requests:
1) Can we nix the "provisional_curie" and "curie" properties from the specs?  These appear to be redundant in that they are implied by the peer URI associated with them.
2) Define the "status" property to correspond to listed states:  {submitted, under_review, rejected, accepted}.  I'm open to other names, or even more states, if needs be.  But I do generally prefer "under_review" over "required-response".
3) I believe for NewTermResponse, for the "requestID" property, "example" should simply be:  25 -- ie, not parenthesized, as its an integer.
4) I think for purposes of clarity, it would make sense in the /TermStatus endpoint for the inbound property "id" to be renamed "requestID".
5) I have mixed opinions about the property name "superclass".  In BAE, we use "parentURI", which I prefer.
6) I would prefer "explanation" (which BAE uses) over "justification".
"submitter" property is ok -- but it does afford the opportunity of being non-unique, ie, if clients other than BAE submit requests.  Incidentally, we call this property "proposerID" in BAE.
"notification request" => "should_email_updates"
7) It may be a bit premature, but an error code (as well as message) might be nice for "ApiErrorResponse".  My general thinking is the message ultimately would be internationalized and therefore variable across clients, while the error code would be fixed across clients.
8) I'm not sure what the point of "new_term" property is.  If the /TermStatus returns "accepted", then by implication the term is effective, whether it was recently approved or not.
9) None of the responses returns a timestamp.  Per the notes / diagram I emailed yesterday, I think it would be helpful -- when possible -- to return timestamps int he responses.  Generally, a "lastModified" timestamp would indicate when a record on the server side was last touched.  Or if that is too ambiguous, then maybe there should be a property like "datetimeApproved".

**Comment by chung88** [comment]
1. @whinis: [OB git-43](https://github.com/OntoloBridge/ontolobridge-project/issues/43)
2. @whinis: done
3. @whinis: done
4. @whinis: done
5. @whinis: needs discussion [OB git-44](https://github.com/OntoloBridge/ontolobridge-project/issues/44)
6. @whinis: needs discussion  [OB git-45](https://github.com/OntoloBridge/ontolobridge-project/issues/45)
7. @whinis: done
8. @whinis: done
9. @whinis: done
