### ISSUE TITLE
Draw a systems architecture diagram

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#30]
There are couple of diagrams feeding into this task that are currently active: 
https://docs.google.com/drawings/d/1R-nIfezUy4o_5KVuvw9Vg7QndsS5_SeO2xp5kEQrEFU/edit

https://docs.google.com/drawings/d/186RBvC4MHdYO9kjXijlqM9VQGUJ2v_Jc0kIdh68PqGY/edit

**Comment by graybeal** [comment]
requires #29
