### ISSUE TITLE
ticketing updates: milestones, single owners

### ISSUE THREAD

**Issue by graybeal** [OntoloBridge/ontolobridge-project#34]
Change the ticketing system for the system to address:

1. Replace the milestone tag with individual tags for each milestone (just the first milestone or two for now?)
2. For those tasks that are in progress or already have owners, assign a single owner (representing the lead of that task

**Comment by handemcginty** [comment]
I edited the labels and assignees, waiting for a second pair of eyes before I close this issue. Thanks.
