### ISSUE TITLE
API validation implementation

### ISSUE THREAD

**Issue by handemcginty** [OntoloBridge/ontolobridge-project#38]
Updating the API so it returns validation for term request submissions.

**Comment by whinis** [comment]
Estimated time to completion is 3 weeks between classes and other projects

**Comment by whinis** [comment]
@graybeal @mdorf Do you have any input as to what the restrictions should be for the validation?

**Comment by mdorf** [comment]
Not sure what you mean by "restrictions". I would expect the following validation to be in place:

1.  Required fields having empty values: "description", "label", and "superclass".
2. Email format validation for the field "email" (if filled out).
3. Boolean validation for the field "notify" (if filled out).

I'd expect an appropriate HTTP Status Code with a list of erroneous fields returned for an invalid input. This thread is a good reference:

https://stackoverflow.com/questions/7939137/right-http-status-code-to-wrong-input

BTW, should "email" be a required field?

**Comment by graybeal** [comment]
Yes to what Misha said (which I slightly edited to make all three sentences describe what to flag

Email should be a required field in my opinion. Bad email fields are no @, not a legal email string per the email name standard, and not a valid email server domain (at least two parts, period-separated, with a valid top-level domain name.

Superclass has to be an identifier, yes? (I've forgotten.) Make sure it is whatever it is supposed to be.

I assume labels are free text, spaces and Unicode allowed. So not much validation you can do there.

Ideally description and label should have an optional language tag (typically '@en', but not always!). And if there are multiple descriptions and labels (for multiple languages), make sure they satisfy the requested format (ideally they should be pairable, but sometimes I think there can be multiple English labels for example?).
