### ISSUE TITLE
CURIE

### ISSUE THREAD

**Issue by chung88** [OntoloBridge/ontolobridge-project#43]
Putative API:/REST/RequestTerm
Output:
provisional CURIE: a temporary CURIE(which includes the token) that can be used as a placeholder, while waiting for a decision on the term
reference: [Technical Proposal OntoloBridge](https://docs.google.com/document/d/1vB9PGXied4gdIXaFHfXyrOg67Nv2y8bTvmeR9LNJgII/edit?usp=sharing)

**Comment by sjeschonek** [comment]
Previously - short term; but this has been updated by john T.
