### ISSUE TITLE
"explanation" vs "justification"

### ISSUE THREAD

**Issue by chung88** [OntoloBridge/ontolobridge-project#45]
"explanation" (which BAE uses) over "justification".
"submitter" property is ok -- but it does afford the opportunity of being non-unique, ie, if clients other than BAE submit requests. Incidentally, we call this property "proposerID" in BAE.
"notification request" => "should_email_updates"

**Comment by sjeschonek** [comment]
> Justification

**Comment by whinis** [comment]
Decision was made to continue to just Justification
