### ISSUE TITLE
Implement initial design to standalone website

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#57]

**Comment by sjeschonek** [comment]
@whinis I'd like to break this up into smaller git tasks -- could you list below some technical milestones for getting web v1.0 up?

**Comment by whinis** [comment]
Developed the following issues for the standalone website 

- [ ] #84 
- [ ] #85 
- [ ] #86

**Comment by whinis** [comment]
All requirements are done, closing issue
