### ISSUE TITLE
Instructions field in Bioportal for how to submit ontolobridge requests

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#76]
To provide custom information in each term request page should a ontology maintainer wish to add. @graybeal

**Comment by sjeschonek** [comment]
Hi @mdorf , can you please be prepared to show off the work you've done on this next meeting (Oct 2nd), and also to provide an outline of next steps?

**Comment by mdorf** [comment]
@sjeschonek, will do my best! BTW, can you provide a text that can be used as default instructions for ontologies. The ontology administrator will have an option of replacing that text, but I do need something default to be displayed.

**Comment by sjeschonek** [comment]
The BioAssay Ontology integrates with OntoloBridge, allowing community users to suggest additions to the public ontology. Complete the template below to submit a term request directly to the ontology maintainer.

> Term Label (required) 
Suggested term name. If a term can be described with multiple synonyms, only list the preferred name here. 
_Example: tissue-based format_

> Term description (required)
A brief definition, description, or usage of your suggested term.  
_Example: Involves the use of a tissue derived from a living organism and is a heterogeneous assay type._

> Superclass (required)
The parent term of the suggested term. The parent term should be an existing entry of the current ontology. The superclass can be selected directly from the 'Classes' viewer on Bioportal's left tree navigation.
_Example: assay format_

> References (optional)
Provide evidence for the existence of the requested term such as PMIDs of papers or links to other resources that describe the term.

> Justification (optional)
Provide any additional information about the requested term here.

**Comment by sjeschonek** [comment]
@whinis , please review placeholder text so @mdorf can move to production.

**Comment by mdorf** [comment]
The change has been deployed to BioPortal production.
