### ISSUE TITLE
Create list of options for intake form

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#80]
Create dropdown list options for user intake form, “primary reason for getting an account”.  

Feel free to update in the comment section below.

Also can list the roles in comment box below.

**Comment by gwytherinadelle** [comment]
Primary reason for requesting an account:
- Manage my team's term submissions
- Submit terms for myself
- Submit terms on behalf of someone else
- Check the status of terms

Role within your organization:
- Informaticist/Programmer
- Biologist
- Chemist
- Scientist (Other)
- Manager/Team Leader

I will continue to think about this and add additional options if I think of any.

**Comment by sjeschonek** [comment]
@whinis For your incorporation during the user signup process
