### ISSUE TITLE
QC Latest BAO release [2.6]

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#81]
Deadline for Sam & Julia to complete: Wednesday 7/29

**Comment by gwytherinadelle** [comment]
Unsure how to QC the first few which are the labels for things in other ontologies? Do we just check those off as good to go?

**Comment by whinis** [comment]
Ya, if they are in other ontologies is just a matter if they are actually in the file properly.

**Comment by gwytherinadelle** [comment]
QC Notes:
- parallel artificial membrane permeability assay has a trailing underscore
- Why were 110 and 2128 found twice (protein-small molecule interaction assay and physical property endpoint respectively)? The merge file that I last have access to seems to only have it occur once. 
- It would be helpful to include the suggested parent class for the new terms in the QC file. As far as I can tell, they look fine aside from the trailing underscore, but only insofar as I recall agreeing to add the terms.

**Comment by sjeschonek** [comment]
I don't' have anything different besides what Julia provided!

**Comment by whinis** [comment]
>Why were 110 and 2128 found twice (protein-small molecule interaction assay and physical property endpoint respectively)? The merge file that I last have access to seems to only have it occur once.

From what I can tell even though I am telling it to only read individual files some of the axioms are subclasses of classes in other files and so the OWLApi reasoner is making a stub class whenever it reasons. Trying to find a good way to eliminate those.
