### ISSUE TITLE
BIOPORTAL SERVER DOWN

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#87]
*Questions marked with + are required. If multiple people are involved in troubleshooting, please indicate the actions each has taken.*

**1. Date of system outage +**

07/23/2020

**2. What actions led to outage +**

Attempted to 'Request New Term' on CLO.

**3. What behavior occurred on BioPortal? How was it different than usual? +**

Received the following error message instead of the term being submitted and returning a submission ID: 
> The following error has occurred: Internal Server Error. Please try again.

**4. What behavior occurred on developer system? How was it different than expected? +**
@whinis 

**5. How did you verify the developer system was working normally? +**
@whinis 

**6. Any other contextual information that suggest the issue is with BioPortal?**
@whinis

**Comment by graybeal** [comment]
Misha is out today, we'll try to have a look in his absence.

**Comment by jvendetti** [comment]
I'm running the full BioPortal stack in my local development environment. It's not clear to me that this is a BioPortal issue. When I click on the "Submit" button to request a new term in CLO for example, BioPortal correctly issues a new term request to the OntoloBridge endpoint: 

http://ontolobridge.css.miami.edu/api/requests/RequestTerm

It's this endpoint that throws a 500 error. Exact message shown in this screen shot:

![Screenshot 2020-07-23 14 52 45](https://user-images.githubusercontent.com/1696923/88342702-be98e880-ccf4-11ea-8f3a-528ad18a8d93.png)

The following screen shot also shows that the correct parameter set is sent to the OntoloBridge endpoint:

![Screenshot 2020-07-23 15 02 24](https://user-images.githubusercontent.com/1696923/88343141-91990580-ccf5-11ea-8303-4dac1e537948.png)

Could someone from the OntoloBridge team check the status of the /RequestTerm endpoint?

**Comment by whinis** [comment]
Just checked and the server was in some locked up state where the swagger was working but not the application. Restarted the server and it appears to be working now. Trying to look further into what went wrong
