### ISSUE TITLE
Definition of Tethering Assays in BAO

### ISSUE THREAD

**Issue by LittleBunnyFooBar** [OntoloBridge/ontolobridge-project#89]
New terms to describe tethering (disulfide trapping) assays in BAO. For further reference, please see [https://journals.sagepub.com/doi/full/10.1177/2472555217732072](url).

We need new terms underneath both bioassay and assay design method. 

**bioassay**
binding assay > protein-small molecule interaction assay > tethering assay

synonyms for tethering assay: disulfide trapping, disulfide tethering assay

**assay design method**
binding assessment method > ligand covalent binding method > cysteine, lysine, methionine, serine, tyrosine, N-terminal, threonine, unnatural amino acid

**Comment by sjeschonek** [comment]
@whinis

**Comment by whinis** [comment]
Has there been any progress on the definitions ?

**Comment by gwytherinadelle** [comment]
@sjeschonek were you going to propose definitions? Or was I supposed to?

**Comment by sjeschonek** [comment]
@gwytherinadelle I believe you were since it you proposed the terms. I was suppose to do a Mass spec definition, but @whinis beat me to it.

**Comment by gwytherinadelle** [comment]
binding assessment method > ligand covalent binding method > cysteine ligand covalent binding method

the cysteine ligand covalent binding method is used to measure binding of a thiol-reactive molecule with a cysteine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > lysine ligand covalent binding method
the lysine ligand covalent binding method is used to measure binding of an amine-reactive molecule with a lysine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > methionine ligand covalent binding method
the methionine ligand covalent binding method is used to measure binding of an thioether-reactive molecule with a methionine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > serine ligand covalent binding method
the serine ligand covalent binding method is used to measure binding of an alcohol-reactive molecule with a serine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > tyrosine ligand covalent binding method
the tyrosine ligand covalent binding method is used to measure binding of a phenol-reactive molecule with a tyrosine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.
 
binding assessment method > ligand covalent binding method > N-terminal ligand covalent binding method
the N-terminal ligand covalent binding method is used to measure binding of an amine-reactive molecule with the N-terminus of a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > threonine ligand covalent binding method
the threonine ligand covalent binding method is used to measure binding of an alcohol-reactive molecule with a threonine residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.

binding assessment method > ligand covalent binding method > unnatural amino acid ligand covalent binding method

the unnatural amino acid ligand covalent binding method is used to measure binding of a reactive molecule with a particular unnatural residue on a protein of interest.  Binding assessment can be measured by protein mass spectrometry or other direct-binding methodology.  Unnatural amino acids can contain a variety of ‘bioorthogonal’ chemical handles.

**Comment by whinis** [comment]
Added for BAO 2.7
BAO_0040033 ligand covalent binding method
BAO_0040034 lysine ligand covalent binding method
BAO_0040035 methionine ligand covalent binding method
BAO_0040036 serine ligand covalent binding method
BAO_0040037 tyrosine ligand covalent binding method
BAO_0040038 N-terminal ligand covalent binding method
BAO_0040039 threonine ligand covalent binding method
BAO_0040040 unnatural amino acid ligand covalent binding method
BAO_0040041 cysteine ligand covalent binding method
