### ISSUE TITLE
Authentication for standalone site

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#93]
Finish authentication system, being sure to incorporate the required fields and dropdowns as discussed:
https://github.com/OntoloBridge/ontolobridge-project/issues/82
https://github.com/OntoloBridge/ontolobridge-project/issues/80

Work with @mdorf to ensure harmonization between new authentication system and BioPortal

**Comment by whinis** [comment]
Initial version of Authentication completed. External Authentication and Api Keys will be a separate issue
