### ISSUE TITLE
[Bioportal-Ontolobridge Server Error]

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#94]
*Questions marked with + are required. If multiple people are involved in troubleshooting, please indicate the actions each has taken. BioPortal team should only be assigned once Question #5 is answered*

**1. Date of system outage +**
08/07/2020

**2. What actions led to outage +**
Requesting terms in CLO

**3. What behavior occurred on BioPortal? How was it different than usual? +**
Error message and reporting below:
`The following error has occurred: Internal Server Error. Please try again.`
![Screen Shot 2020-08-07 at 2 01 53 PM](https://user-images.githubusercontent.com/34752203/89674771-b2955500-d8b6-11ea-8c52-e16d88669e42.png)

**4. What behavior occurred on developer system? How was it different than expected? **

**5. How did you verify the developer system was working normally? +**

**6. Any other contextual information that suggest the issue is with BioPortal?**

**Comment by whinis** [comment]
I have restarted the server and fixed some exceptions filling the logs but likely unrelated. Please try again and let me know if the breaks again.

**Comment by whinis** [comment]
Thankfully I now have proper error monitoring implemented last week. I noticed the requests sent was missing the superclass and did not have the parent_uri either. 
![image](https://user-images.githubusercontent.com/7612064/90647489-5c090e80-e206-11ea-8696-9e08ccd7671c.png)

So I am going to tag @mdorf and see if he can determine why the superclass is not being sent and if they have updated to parent_uri interally yet ? If not I can apply a fix myside

**Comment by mdorf** [comment]
@whinis, when had this change been communicated to me? I don't find any mention of it in my inbox or anywhere else.

Can you please specify what exactly needs to be updated? Had there been any other changes in the document structure we should be aware of?

In general, a good practice is to provide a grace period for changes like these that break our production site and require a production release on our end to be addressed.

This URL no longer works either:

http://ontolobridge.ccs.miami.edu/api

**Comment by whinis** [comment]
I am trying to figure out when exactly that change when out, might have been whenever I was fixing another bug. I was more worried about it sending undefined however as its easy to rollback that name of the API. I am looking into the API issue.

**Comment by whinis** [comment]
Ok http://ontolobridge.ccs.miami.edu/api should now work, I am not entirely sure why it stopped working but http://ontolobridge.ccs.miami.edu/api/ still did. Now both should.

**Comment by whinis** [comment]
@mdorf To keep you in the loop I can see that the push containing the error handling erroneously also included the change to parent_uri from superclass and that has been reverted. Also a bug in the swagger page that included the csrf endpoint and incorrectly showed the endpoint as base instead of /api has been corrected and just pushed.

**Comment by mdorf** [comment]
This appears to be fixed after code revert:
<img width="1210" alt="Screen Shot 2020-08-20 at 11 27 39 AM" src="https://user-images.githubusercontent.com/2042070/90810725-4a903700-e2d8-11ea-8b1a-d16e43792df8.png">

**Comment by whinis** [comment]
@mdorf It submitted but the superclass was blank in this case it appears which was my original worry.

**Comment by mdorf** [comment]
@whinis, I no longer see the "superclass" attribute in the model:

<img width="816" alt="Screen Shot 2020-08-20 at 11 44 52 AM" src="https://user-images.githubusercontent.com/2042070/90812279-b378ae80-e2da-11ea-8adc-5d6280421151.png">

We haven't changed any code on our end since the time this used to work, so it must be something on yours.

**Comment by whinis** [comment]
Thats the response on status and not requests although it likely also needs to be updated to include the superclass and I will create an issue for that. 

However looking at the code I take exactly what you give me and insert it into the database without manipulation. It appears to be a blank string and is something I should likely check for and will in the future after I finish authentication. I can add in code quickly to log all requests for now but whenever the parent_uri issue was noticed the superclass was sent as undefined.

**Comment by sjeschonek** [comment]
Still getting an error on my end @whinis ...let me know when the code is updated
![Screen Shot 2020-08-20 at 3 45 23 PM](https://user-images.githubusercontent.com/34752203/90817713-2e05f600-e2fc-11ea-8ee5-d3e78d2c689d.png)

**Comment by whinis** [comment]
This caused a new error, my database appearntly went away, currently looking into why

**Comment by whinis** [comment]
@sjeschonek You should be able to submit again even if the correct superclass may not be attached.

**Comment by mdorf** [comment]
I'm seeing something abnormal on our end that hadn't been the case before. Namely, if you look at the label for the superclass (see any of the above screenshots), it displays the label of the class itself, not that of its superclass. I wonder if the recent change the Jennifer did to address ncbo/bioportal_web_ui#146 somehow impacted this functionality. Will investigate further...

**Comment by mdorf** [comment]
Just wanted to let you know that the issues with passing the superclass in BioPortal has been fixed. Please validate on your end.

**Comment by whinis** [comment]
Validated
