### ISSUE TITLE
Create new 'mass spectrometry' term

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#96]
Create new term 'mass spectrometry' as child under 'physical detection method'
physical detection method > mass spectrometry

Since basic detection method is the same whether label or label free, no need to specify (this detail would be linked to design method). Artifacts would not differ between these labeled or unlabeled methods.

Remove the term:
physical detection method > label-free > mass spectrometry

**Comment by sjeschonek** [comment]
Reparent term; @whinis

**Comment by whinis** [comment]
Current Description, does this need to be changed

> This method is used to detect compounds that are bound to the protein targets. The unbound compounds are separated by affinity based, size exclusion, or ultrafiltration methods. The bound compounds are eluted from the protein and detected by mass spectrometry. Based on the separation method, the throughput varies: between 200-2700 compounds can be loaded in each run for separation.
>Mass spectrometry is used to determine the chemical structure of molecules. The samples are vaporized, followed by ionization and then the mass to charge ratio of the particles is analyzed.

**Comment by sjeschonek** [comment]
@gwytherinadelle @sjeschonek review description

**Comment by sjeschonek** [comment]
From wiki:

Mass spectrometry (MS) is an analytical technique that measures the mass-to-charge ratio of ions. The results are typically presented as a mass spectrum, a plot of intensity as a function of the mass-to-charge ratio. Mass spectrometry is used in many different fields and is applied to pure samples as well as complex mixtures.

A mass spectrum is a plot of the ion signal as a function of the mass-to-charge ratio. These spectra are used to determine the elemental or isotopic signature of a sample, the masses of particles and of molecules, and to elucidate the chemical identity or structure of molecules and other chemical compounds.

In a typical MS procedure, a sample, which may be solid, liquid, or gaseous, is ionized, for example by bombarding it with electrons. This may cause some of the sample's molecules to break into charged fragments or simply become charged without fragmenting. These ions are then separated according to their mass-to-charge ratio, for example by accelerating them and subjecting them to an electric or magnetic field: ions of the same mass-to-charge ratio will undergo the same amount of deflection.[1] The ions are detected by a mechanism capable of detecting charged particles, such as an electron multiplier. Results are displayed as spectra of the signal intensity of detected ions as a function of the mass-to-charge ratio. The atoms or molecules in the sample can be identified by correlating known masses (e.g. an entire molecule) to the identified masses or through a characteristic fragmentation pattern.

**Comment by whinis** [comment]
I propose the following definition 
`Detection techniques that use the the variation in mass-to-charge ratio of ions within a sample  to measure the quantitative and qualitative information regarding the sample. The sample can be in solid, liquid, or gaseous state and be hard or soft ionized depending on the stability of the sample and desired parameters to be measure. It may be used exclusively as a detection technique or used in tandem with purification methods such as liquid chromatography. `

**Comment by gwytherinadelle** [comment]
@whinis looks good to me
